plugin: aws_ec2
regions:
  - us-east-1
filters:
  "tag:Role": SchedemyWebServer
  instance-state-name: running
keyed_groups:
  - key: tags.Role
    prefix: role
compose:
  ansible_host: public_ip_address